name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: windows-latest
    steps:
    - uses: abelsquidhead/testinput@release/v1
      name: "testinput"
      with:
        myInput: abc123