name: "test input"
on: [pull_request, push]

jobs:
  testInput:
    runs-on: windows-latest
    steps:
    - uses: abelsquidhead/testinput@master
      name: "testinput"
      with:
        myInput: "%GITHUB_WORKSPACE%"
